# Generated by Django 2.0.2 on 2018-03-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coinsName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coinsname', models.CharField(help_text='Enter field documentation', max_length=20)),
            ],
            options={
                'ordering': ['-coinsname'],
            },
        ),
    ]
