# Generated by Django 2.0.2 on 2018-03-14 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='coinsName',
        ),
    ]
